[package]
name = "{{project-name}}"
authors = ["{{authors}}"]
version = "0.1.0"
edition = "2021"

[features]
library = []

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
sylvia = "2.0.0-rc.1"
cw-storage-plus = "3.0.0-rc.2"

[dev-dependencies]
sylvia = { version = "2.0.0-rc.1", features = ["mt"] }
