[package]
name = "cw-sylvia-template"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
cosmwasm-std = { version = "1", features = ["staking"] }
sylvia = "0.7"
serde = "1.0.180" # required by sylvia
schemars = "0.8" # required by sylvia
cosmwasm-schema = "1.3"
cw-storage-plus = "1.2"
